name: Main branch workflow

# Runs when commits are pushed to the main branch
# - Checkouts the pushed branch
# - Builds and tests the project
# - Deploys the application to Github Pages (branches/[branch name])
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: martinmoscovich/gh-actions/.github/workflows/npm-build.yml@v1
    with:
      node_version: 14
      dist_dir: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch

      - name: Deploy to GH Pages
        uses: martinmoscovich/gh-actions/gh-deploy@v1
        with:
          to: branches/${{ steps.extract_branch.outputs.current_branch }}
          environment_name: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
