name: Test Milestone


on:
  milestone:
    types: [created, opened, edited]

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query issuesForMilestone($searchQuery: String!) {
                search(first: 100, type: ISSUE, query: $searchQuery) {
                  edges {
                    node {
                      ... on PullRequest {
                        number
                        title
                        body
                      }
                    }
                  }
                }
            }`

            const result = await github.graphql(query, {searchQuery: `is:pr user:${owner} repo:${repo} milestone:${milestoneName}`})
            console.log(result)
