name: PRs closed

# Runs when commits are pushed to a branch associated with a PRs that targets the main branch
# - Checkouts the pushed branch
# - Builds and tests the project
# - Deploys the application to Github Pages (branches/[branch name])
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  prune:
    name: Prune
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch
        
      - name: Prunes enviroment and files
        uses: martinmoscovich/gh-actions/prune-deployment@main
        with:
          to: branches/${{ steps.extract_branch.outputs.current_branch }}
          environment_name: branch-${{ steps.extract_branch.outputs.current_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}