name: PRs workflow

# Runs when commits are pushed to a branch associated with a PRs that targets the main branch
# - Checkouts the pushed branch
# - Builds and tests the project
# - Deploys the application to Github Pages (branches/[branch name])
on:
  pull_request:
    types: [edited]
    branches:
      - main

jobs:
  milestone:
    name: Check if milestone is set
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.request("GET /repos/{owner}/{repo}/pulls/{pr}", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pr: context.payload.pull_request.number
            });
            if (data.milestone) {
              core.info(`This pull request has a milestone set: ${data.milestone.title}`);
            } else {
              core.setFailed(`A maintainer needs to set the milestone for this pull request.`);
  