name: PRs workflow

# Runs when commits are pushed to a branch associated with a PRs that targets the main branch
# - Checkouts the pushed branch
# - Builds and tests the project
# - Deploys the application to Github Pages (branches/[branch name])
on:
  pull_request:
    types: [edited]
    branches:
      - main

jobs:
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.milestone == null
        run: exit 1
  