name: PRs workflow

# Runs when commits are pushed to a branch associated with a PRs that targets the main branch
# - Checkouts the pushed branch
# - Builds and tests the project
# - Deploys the application to Github Pages (branches/[branch name])
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  milestone:
    name: Check if milestone is set
    runs-on: ubuntu-latest
    steps:
      - name: Check milestone
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.request("GET /repos/{owner}/{repo}/pulls/{pr}", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pr: context.payload.pull_request.number
            });
            if (data.milestone) {
              core.info(`This pull request has a milestone set: ${data.milestone.title}`);
            } else {
              core.setFailed(`A maintainer needs to set the milestone for this pull request.`);
            }
  build:
    uses: martinmoscovich/gh-actions/.github/workflows/npm-build.yml@v1
    with:
      node_version: 14
      dist_dir: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch or tag name
        uses: tj-actions/branch-names@v5
        id: extract_branch
        
      - name: Deploy to GH Pages
        uses: martinmoscovich/gh-actions/gh-deploy@main
        with:
          to: branches/${{ steps.extract_branch.outputs.current_branch }}
          environment_name: branch-${{ steps.extract_branch.outputs.current_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          

