name: Releases workflow

# Run for Main releases when the associated milestone is closed
# - Checkouts the default branch
# - Builds and tests the project
# - Creates a tag and a new release with the compressed artifact using the name of the Milestone
# - Deploys the application to Github Pages (releases/[release name])
on:
  milestone:
    types: [closed]

jobs:
  build:
    uses: martinmoscovich/gh-actions/.github/workflows/npm-build.yml@v1
    with:
      node_version: 14
      dist_dir: dist
      source_ref: main

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        uses: martinmoscovich/gh-actions/release@v1
        with:
          source_ref: main
          tag: ${{ github.event.milestone.title }}
          release_filename: ${{ github.event.repository.name }}-${{ github.event.milestone.title }}
          description: ${{ github.event.milestone.description }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GH Pages
        uses: martinmoscovich/gh-actions/gh-deploy@v1
        with:
          to: releases/${{ github.event.milestone.title }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
