name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Substitute Environment Variables in files
        uses: martinmoscovich/gh-actions/envsubst@main
        with:
          path: '${{ GITHUB_WORKSPACE }}/src'
          file_pattern: '*'
          prefix: '@{'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          destination_dir: ./main
